GET http://localhost:56861/characters/random
Accept: application/json

###

GET http://localhost:56861/characters/random/with-delay
Accept: application/json

###

GET http://localhost:56861/characters/random/with-errors
Accept: application/json

###

GET http://localhost:8080/characters/random-list
Accept: text/event-stream

###